version: '3'
services:
  appwrite:
    image: appwrite/appwrite:latest
    ports:
      - "80:80"
    volumes:
      - appwrite-data:/var/lib/appwrite
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - appwrite
    networks:
      - app-network

networks:
  app-network:

volumes:
  appwrite-data:
